In [2]:
import pandas as pd 
import numpy as np

In [3]:
book_path = "/Users/minaungthu/Documents/KU /1st year/2nd Semester/computer programming/project/dataset/Books.csv" 
user_path = "/Users/minaungthu/Documents/KU /1st year/2nd Semester/computer programming/project/dataset/Users.csv"
rating_path = "/Users/minaungthu/Documents/KU /1st year/2nd Semester/computer programming/project/dataset/Ratings.csv"

book_df = pd.read_csv(book_path)
user_df = pd.read_csv(user_path)
rating_df = pd.read_csv(rating_path)

/var/folders/zb/bss23kdn25bg5_5cnl9dyv600000gn/T/ipykernel_10106/586059617.py:5: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  book_df = pd.read_csv(book_path)

In [4]:
book_df.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [5]:
book_df = book_df[['ISBN','Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher','Image-URL-L']]

In [6]:
book_df.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-L'],
      dtype='object')

In [7]:
user_df.columns
user_df.rename(columns={"User-ID":'user_id',"Location":"location", "Age":'age'},inplace=True)
user_df.columns

Index(['user_id', 'location', 'age'], dtype='object')

In [8]:
rating_df.columns

Index(['User-ID', 'ISBN', 'Book-Rating'], dtype='object')

In [9]:
rating_df.rename(columns={"User-ID":"user_id", "Book-Rating":"rating"},inplace=True)
rating_df.columns

Index(['user_id', 'ISBN', 'rating'], dtype='object')

In [10]:
print(f"book_df size: {book_df.shape} \nuser_df size : {user_df.shape} \nrating_df size: {rating_df.shape}")

book_df size: (271360, 6)
user_df size : (278858, 3)
rating_df size: (1149780, 3)

In [11]:
#storing users who rated at least 100 books 
x = rating_df['user_id'].value_counts() > 100

In [12]:
x[x].shape

(1825,)

In [13]:
y= x[x].index
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       238186,  99441, 187410, 262070,  70183,  40553,  39345, 266283, 189666,
       140879],
      dtype='int64', name='user_id', length=1825)

In [14]:
rating_df = rating_df[rating_df['user_id'].isin(y)]
rating_df.head()

     user_id        ISBN  rating
412   276925  0006511929       0
413   276925  002542730X      10
414   276925  0060520507       0
415   276925  0060930934       0
416   276925  0060951303       0

In [15]:
rating_df.shape

(656605, 3)

In [16]:
books_with_ratings = rating_df.merge(book_df, on='ISBN')
books_with_ratings.head()

,user_id,ISBN,rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,276925,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,276925,0060520507,0,"Sushi for Beginners : A Novel (Keyes, Marian)",Marian Keyes,2003,William Morrow,http://images.amazon.com/images/P/0060520507.0...
2,276925,0060930934,0,Wasted : A Memoir of Anorexia and Bulimia,Marya Hornbacher,1999,Perennial,http://images.amazon.com/images/P/0060930934.0...
3,276925,0060951303,0,La casa de los espÃ­ritus,Isabel Allende,1995,Rayo,http://images.amazon.com/images/P/0060951303.0...
4,276925,0140154078,6,The Music of Chance,Paul Auster,1993,Penguin Books,http://images.amazon.com/images/P/0140154078.0...

In [17]:
number_rating = books_with_ratings.groupby('Book-Title')['rating'].count().reset_index()

In [18]:
number_rating.head()

                                          Book-Title  rating
0   A Light in the Storm: The Civil War Diary of ...       3
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [19]:
number_rating.rename(columns={'rating':'num_of_rating'},inplace=True)

In [20]:
number_rating.head()

                                          Book-Title  num_of_rating
0   A Light in the Storm: The Civil War Diary of ...              3
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [21]:
final_rating = books_with_ratings.merge(number_rating, on='Book-Title')
final_rating.head()

,user_id,ISBN,rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L,num_of_rating
0,276925,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,105
1,276925,0060520507,0,"Sushi for Beginners : A Novel (Keyes, Marian)",Marian Keyes,2003,William Morrow,http://images.amazon.com/images/P/0060520507.0...,16
2,276925,0060930934,0,Wasted : A Memoir of Anorexia and Bulimia,Marya Hornbacher,1999,Perennial,http://images.amazon.com/images/P/0060930934.0...,12
3,276925,0060951303,0,La casa de los espÃ­ritus,Isabel Allende,1995,Rayo,http://images.amazon.com/images/P/0060951303.0...,8
4,276925,0140154078,6,The Music of Chance,Paul Auster,1993,Penguin Books,http://images.amazon.com/images/P/0140154078.0...,6

In [22]:
#taking books with at least 30 ratings 
final_rating = final_rating[final_rating['num_of_rating'] >= 30]
final_rating.head()

,user_id,ISBN,rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L,num_of_rating
0,276925,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,105
5,276925,0140327592,0,Matilda,Roald Dahl,1990,Viking Penguin Inc,http://images.amazon.com/images/P/0140327592.0...,79
12,276925,0316666343,0,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,430
15,276925,0385504209,8,The Da Vinci Code,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,335
32,276925,0679745580,0,In Cold Blood (Vintage International),TRUMAN CAPOTE,1994,Vintage,http://images.amazon.com/images/P/0679745580.0...,30

In [23]:
final_rating.shape

(148590, 9)

In [24]:
final_rating.drop_duplicates(['user_id','Book-Title'],inplace=True)
final_rating.shape

(145469, 9)

In [25]:
book_pivot = final_rating.pivot_table(columns='user_id', index='Book-Title', values= 'rating')
book_pivot

user_id,183,254,507,882,1424,1435,1733,1903,2033,2110,...,276018,276463,276680,276925,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16 Lighthouse Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1984,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010: Odyssey Two,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
You Belong to Me and Other True Cases (Ann Rule's Crime Files: Vol. 2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zlata's Diary: A Child's Life in Sarajevo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
book_pivot.shape

(2372, 1804)

In [40]:
book_pivot.fillna(0, inplace=True)
book_pivot

user_id,183,254,507,882,1424,1435,1733,1903,2033,2110,...,276018,276463,276680,276925,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
You Belong to Me and Other True Cases (Ann Rule's Crime Files: Vol. 2),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zlata's Diary: A Child's Life in Sarajevo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
!pip install scipy

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: scipy in /Users/minaungthu/miniforge3/envs/opencv-env/lib/python3.13/site-packages (1.15.2)
Requirement already satisfied: numpy<2.5,>=1.23.5 in /Users/minaungthu/miniforge3/envs/opencv-env/lib/python3.13/site-packages (from scipy) (2.2.3)

In [29]:
#since the dataset is mostly sparse, we will apply sparse matrix 
from scipy.sparse import csr_matrix
book_sparse = csr_matrix(book_pivot)
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [30]:
!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: scikit-learn in /Users/minaungthu/miniforge3/envs/opencv-env/lib/python3.13/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /Users/minaungthu/miniforge3/envs/opencv-env/lib/python3.13/site-packages (from scikit-learn) (2.2.3)
Requirement already satisfied: scipy>=1.6.0 in /Users/minaungthu/miniforge3/envs/opencv-env/lib/python3.13/site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /Users/minaungthu/miniforge3/envs/opencv-env/lib/python3.13/site-packages (from scikit-learn) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/minaungthu/miniforge3/envs/opencv-env/lib/python3.13/site-packages (from scikit-learn) (3.6.0)

In [31]:
from sklearn.neighbors import NearestNeighbors
#using brute force since the input data is very sparse
model = NearestNeighbors(algorithm= 'brute')

In [32]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [33]:
distance, suggestion = model.kneighbors(book_pivot.iloc[1,:].values.reshape(1,-1), n_neighbors=6 )

In [34]:

for i in suggestion[0]:
    print(book_pivot.index[i])

16 Lighthouse Road
Hurricane Bay
Acts of Love
About Face
Everything to Gain
Stay Out of the Basement (Goosebumps, No 2)

In [35]:

def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1), n_neighbors=6 )
    
    for i in range(len(suggestion)):
            books = book_pivot.index[suggestion[i]]
            for j in books:
                if j == book_name:
                    print(f"You searched '{book_name}'\n")
                    print("The suggested books are: \n")
                else:
                    print(j)

In [54]:
a = np.where(book_pivot.index == "1984")[0][0]
print(a)

2

In [36]:
book_pivot.head(10)

user_id,183,254,507,882,1424,1435,1733,1903,2033,2110,...,276018,276463,276680,276925,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
204 Rosewood Lane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2061: Odyssey Three,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
311 Pelican Court,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
recommend_book("1984")

You searched '1984'

The suggested books are:

Lying Awake
The Fourth Deadly Sin
Acts of Love
Another City, Not My Own: A Novel in the Form of a Memoir
Everything to Gain

In [38]:
book_names = book_pivot.index

In [39]:
import pickle
pickle.dump(model,open('specs/model.pkl','wb'))
pickle.dump(book_names,open('specs/book_names.pkl','wb'))
pickle.dump(final_rating,open('specs/final_rating.pkl','wb'))
pickle.dump(book_pivot,open('specs/book_pivot.pkl','wb'))